import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, setRequestLocale } from "next-intl/server";
import React from "react";
import "./globals.css";
import { getDirectionClass } from "@/lib/TextDirection";
import NextToploader from "nextjs-toploader";
import { QueryProvider } from "@/providers/queryClientProvider";
import { NuqsProvider } from "@/providers/nuqs-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{
    locale: string;
  }>;
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  setRequestLocale(locale);

  const messages = await getMessages();
  const dir = getDirectionClass(locale);

  return (
    <html lang={locale} dir={dir} suppressHydrationWarning>
      <body
        className={`antialiased max-w-dvw overflow-x-hidden`}
        suppressHydrationWarning
      >
        <QueryProvider>
          <NextToploader color="var(--primary)" />
          <NextIntlClientProvider locale={locale} messages={messages}>
            <NuqsProvider>{children}</NuqsProvider>
          </NextIntlClientProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
